### ISSUE TITLE
depends on unreleased libfabric-1.3

### ISSUE THREAD

**Issue by ghost** [cisco/usnic_tools#9]
hi,

http://ofiwg.github.io/libfabric/ , the latest libfabric is version 1.2. Why it depends on unreleased libfabric?

```
<mock-chroot>sh-4.3# pwd
/builddir/build/BUILD/libusnic_verbs-2.0.0/usnic_tools-1.0.0.0
<mock-chroot>sh-4.3# grep -n -C 1  1.3 *
README.md-42-The usnic_tools package requires [Libfabric](http://libfabric.org),
README.md:43:version 1.3 or higher, built with Cisco usNIC support.
README.md-44-
--
configure.ac-94-dnl Make sure we have a new enough libfabric
configure.ac:95:AC_MSG_CHECKING([if libfabric >=v1.3])
configure.ac-96-AC_COMPILE_IFELSE([AC_LANG_PROGRAM([[#include <rdma/fabric.h>
--
configure.ac-101-#elif FI_MAJOR_VERSION == 1 && FI_MINOR_VERSION < 3
configure.ac:102:#error libfabric version too old (<1.3)
configure.ac-103-#endif
--
configure.ac-106-    [AC_MSG_RESULT([no])
configure.ac:107:     AC_MSG_WARN([usnic-tools requires libfabric >=v1.3])
configure.ac-108-     AC_MSG_ERROR([Cannot continue])])
<mock-chroot>sh-4.3# 
```

**Comment by jsquyres** [comment]
Greetings @HonggangLI; thanks for your interest in the usNIC tools package.

There's two reasons that usnic_tools depends on libfabric v1.3:
1. We used a usNIC extension in libfabric to query for the detailed status of the usNIC devices.  This extension was added to (the upcoming) libfabric v1.3.
2. Libfabric v1.3 is estimated to be released by the end of March / beginning of April.

Meaning: we released this before libfabric v1.3 was available in anticipation of libfabric v1.3 being available in the immediate future.  If you want to do some testing, [nightly tarballs of libfabric are available here](http://www.openfabrics.org/downloads/ofiwg/nightly_tarballs/v1.2.x/) -- anything from mid-March 2016 onwards or so should be fine.

**Comment by ghost** [comment]
Ping? Any update? Thanks

**Comment by jsquyres** [comment]
@HonggangLI v1.3.0 has not been released yet.  Have you been able to use one of the v1.3.0 pre-release tarballs (e.g., a nightly snapshot tarball, or an rc tarball)?

**Comment by jsquyres** [comment]
@HonggangLI Libfabric v1.3.0 was just released: https://github.com/ofiwg/libfabric/releases/tag/v1.3.0.

Let me know if you have problems with the released version.
